# Generated by Django 4.0.5 on 2022-06-09 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='homeC',
            new_name='cartoon',
        ),
    ]
