# Generated by Django 4.0.5 on 2022-06-08 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dangnhap', '0002_rename_password_account_password1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account',
        ),
    ]
